Return-Path: <linux-arm-msm+bounces-44357-lists+linux-arm-msm=lfdr.de@vger.kernel.org>
X-Original-To: lists+linux-arm-msm@lfdr.de
Delivered-To: lists+linux-arm-msm@lfdr.de
Received: from ny.mirrors.kernel.org (ny.mirrors.kernel.org [147.75.199.223])
	by mail.lfdr.de (Postfix) with ESMTPS id 3F6DBA0598F
	for <lists+linux-arm-msm@lfdr.de>; Wed,  8 Jan 2025 12:23:24 +0100 (CET)
Received: from smtp.subspace.kernel.org (relay.kernel.org [52.25.139.140])
	(using TLSv1.2 with cipher ECDHE-ECDSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by ny.mirrors.kernel.org (Postfix) with ESMTPS id 4791C160A69
	for <lists+linux-arm-msm@lfdr.de>; Wed,  8 Jan 2025 11:22:59 +0000 (UTC)
Received: from localhost.localdomain (localhost.localdomain [127.0.0.1])
	by smtp.subspace.kernel.org (Postfix) with ESMTP id 0755F1F76DE;
	Wed,  8 Jan 2025 11:22:57 +0000 (UTC)
Authentication-Results: smtp.subspace.kernel.org;
	dkim=pass (2048-bit key) header.d=kernel.org header.i=@kernel.org header.b="E1j5mIjD"
X-Original-To: linux-arm-msm@vger.kernel.org
Received: from smtp.kernel.org (aws-us-west-2-korg-mail-1.web.codeaurora.org [10.30.226.201])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by smtp.subspace.kernel.org (Postfix) with ESMTPS id D17F61A072A;
	Wed,  8 Jan 2025 11:22:56 +0000 (UTC)
Authentication-Results: smtp.subspace.kernel.org; arc=none smtp.client-ip=10.30.226.201
ARC-Seal:i=1; a=rsa-sha256; d=subspace.kernel.org; s=arc-20240116;
	t=1736335376; cv=none; b=Yroo/ytoroRAruiFVznR6HnAJzfJDkjhLJj9b5Cgh58neDDJZgIi2+s+6XRzW3gkWdx5GuOsHfLg42niaVdzmdt0gcQ2DQ2quSQ1TXjlgLhCdfTksAnyn+BO3wLlMrRt+dsQnJlNRt6LYcMxooySdXVVSK1U232gdgzZ1ou9iZk=
ARC-Message-Signature:i=1; a=rsa-sha256; d=subspace.kernel.org;
	s=arc-20240116; t=1736335376; c=relaxed/simple;
	bh=q2HYqSrkEhzFCsWzL/6ZeJhSbwr1mbpb81gzBIiubMQ=;
	h=Date:Message-ID:From:To:Cc:Subject:In-Reply-To:References:
	 MIME-Version:Content-Type; b=jvGO8WTH7hNOtzoPgjBbKTuYuvOByZwJAfE30G+jovirFDDbJ0/UB9Kk9PDCj5GQGLCxQcetkpIZZh/oulIGbgqzwoUzTBBe2oqla1Mjjb6A84kVBNlyZitysPt0cMw7++YVJeJ5gWZjg1kSMNOb9k9rW5LmMEgAf21b0GCHjfw=
ARC-Authentication-Results:i=1; smtp.subspace.kernel.org; dkim=pass (2048-bit key) header.d=kernel.org header.i=@kernel.org header.b=E1j5mIjD; arc=none smtp.client-ip=10.30.226.201
Received: by smtp.kernel.org (Postfix) with ESMTPSA id 4D73AC4CEDD;
	Wed,  8 Jan 2025 11:22:56 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=kernel.org;
	s=k20201202; t=1736335376;
	bh=q2HYqSrkEhzFCsWzL/6ZeJhSbwr1mbpb81gzBIiubMQ=;
	h=Date:From:To:Cc:Subject:In-Reply-To:References:From;
	b=E1j5mIjDN2AEZ1LWo6zhBd0Zr3bk+qK+/UKdaUMexMQxGpOpnRhgfHbFtzUZLoNfw
	 JeNLBmFwtO6CadBVQb7xJ2atPFlsNJYp1bKIFkNsv+1x1fMEtRyh8qLpRP4CMORgMo
	 /FbE/fj4P/UVB1Ld0SIJrKILtPJTbA5GORgDQFrzR3aO0EVpcvqmpnDr8g9jjPTTPd
	 l8gZguiUwrO5N8znYW2DJfzwLXMyAaHB8nnqW8oDPn0SP1RJGC1NhcrqfPMKMLLaHK
	 WQtQbk1YsVyUz40qrAkeF2iGGEfrPyr4qL781ZO8y23cSwFH5pCIlT5QEqHaebtK68
	 UTZyBdoH/iHKA==
Received: from sofa.misterjones.org ([185.219.108.64] helo=goblin-girl.misterjones.org)
	by disco-boy.misterjones.org with esmtpsa  (TLS1.3) tls TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
	(Exim 4.95)
	(envelope-from <maz@kernel.org>)
	id 1tVU9G-00A7Ox-Ab;
	Wed, 08 Jan 2025 11:22:54 +0000
Date: Wed, 08 Jan 2025 11:22:53 +0000
Message-ID: <86v7upwnw2.wl-maz@kernel.org>
From: Marc Zyngier <maz@kernel.org>
To: Yogesh Lal <quic_ylal@quicinc.com>
Cc: Thomas Gleixner <tglx@linutronix.de>,
	<linux-arm-kernel@lists.infradead.org>,
	<linux-kernel@vger.kernel.org>,
	<linux-arm-msm@vger.kernel.org>
Subject: Re: [PATCH v2] irqchip: gic-v3: Handle failure case of CPU enters low power state
In-Reply-To: <20241220093907.2747601-1-quic_ylal@quicinc.com>
References: <20241220093907.2747601-1-quic_ylal@quicinc.com>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI-EPG/1.14.7 (Harue)
 FLIM-LB/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL-LB/10.8 EasyPG/1.0.0 Emacs/29.4
 (aarch64-unknown-linux-gnu) MULE/6.0 (HANACHIRUSATO)
Precedence: bulk
X-Mailing-List: linux-arm-msm@vger.kernel.org
List-Id: <linux-arm-msm.vger.kernel.org>
List-Subscribe: <mailto:linux-arm-msm+subscribe@vger.kernel.org>
List-Unsubscribe: <mailto:linux-arm-msm+unsubscribe@vger.kernel.org>
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
X-SA-Exim-Connect-IP: 185.219.108.64
X-SA-Exim-Rcpt-To: quic_ylal@quicinc.com, tglx@linutronix.de, linux-arm-kernel@lists.infradead.org, linux-kernel@vger.kernel.org, linux-arm-msm@vger.kernel.org
X-SA-Exim-Mail-From: maz@kernel.org
X-SA-Exim-Scanned: No (on disco-boy.misterjones.org); SAEximRunCond expanded to false

On Fri, 20 Dec 2024 09:39:07 +0000,
Yogesh Lal <quic_ylal@quicinc.com> wrote:
> 
> Adding a new condition in gic_cpu_pm_notifier to address instances
> where the CPU fails to enter low power mode (CPU_PM_ENTER_FAILED).
> The CPU_PM framework signals CPU_PM_ENTER_FAILED upon such failures.
> 
> When the CPU attempts to enter low power mode, it disables the
> redistributor and Group 1 interrupts and reinitializes the system
> registers upon wakeup.
> 
> In case of failure while entering low power mode, it is necessary
> to re-enable the redistributor and Group 1 interrupts to restore
> normal operation.
> 
> Signed-off-by: Yogesh Lal <quic_ylal@quicinc.com>

Acked-by: Marc Zyngier <maz@kernel.org>

	M.

-- 
Without deviation from the norm, progress is not possible.

